name = "AtomicSymmetries"
uuid = "7e24f7a5-8a44-4f91-9a93-7ee03df51e54"
authors = ["Lorenzo Monacelli <mesonepigreco@gmail.com>"]
version = "0.10.2"

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Spglib = "f761d5c5-86db-4880-b97f-9680a7cccfb5"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Bumper = "^0.7"
Spglib = "0.9.4"
StaticArrays = "^1.9"
julia = "1.8"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"

[targets]
test = ["Test", "PyCall", "DelimitedFiles", "Random", "Unitful", "UnitfulAtomic", "PhysicalConstants"]
